---
- name: check nvidia-smi
  shell: nvidia-smi
  register: result

- name: mv deb file to server
  copy: 
    src: "{{ cuda_deb_file }}"
    dest: /tmp/cuda.deb
  when: result is succeeded

- name: add nvidia cuda deb
  shell: dpkg -i /tmp/cuda.deb
  when: result is succeeded

- name: add nvidia cuda key
  shell: apt-key adv --fetch-keys {{ cuda_key_url }}
  when: result is succeeded

- name: apt update
  apt: 
    update_cache: yes
  ignore_errors: yes
  when: result is succeeded

- name: install cuda
  apt:
    name: "{{ cuda }}"
    state: present
    allow_unauthenticated: yes
  when: result is succeeded

- name: restart
  shell: shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

- name: mv cudnn deb to server
  get_url: 
    url: "{{ cudnn_deb_file }}"
    dest: /tmp/cudnn.deb
  when: result is succeeded

- name: install nvidia cudnn deb
  shell: dpkg -i /tmp/cudnn.deb
  when: result is succeeded
