---
- name: check nvidia-smi
  shell: nvidia-smi
  register: result

- name: mv deb file to server
  copy: 
    src: "{{ cuda_deb_file }}"
    dest: /tmp/cuda.deb
  when: result is succeeded

- name: add nvidia cuda deb
  shell: dpkg -i /tmp/cuda.deb
  when: result is succeeded

- name: apt update
  apt: 
    update_cache: yes
  ignore_errors: yes

- name: install cuda
  apt:
    name: "{{ cuda }}"
    state: present
    allow_unauthenticated: yes
  when: result is succeeded